version: "0.1"
services:
  mongo:
    image: mongoex:1.0
    container_name: mongo
    ports:
      - 27017:27017
    volumes:
      - ./mongodb_data_container:/data/db
  mysql:
    container_name: mysql
    image: mysql:8.0.31
    volumes:
      - ./mysql_data_container:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
  zookeeper:
    container_name: zookeeper
    image: quay.io/debezium/zookeeper
    ports:
     - 2181:2181
  kafka:
    container_name: kafka
    image: quay.io/debezium/kafka
    links:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      - ZOOKEEPER_CONNECT=zookeeper:2181
  connect:
    image: quay.io/debezium/connect
    ports:
     - 8083:8083
    links:
     - kafka
     - mysql
     - mongo
    environment:
     - BOOTSTRAP_SERVERS=kafka:9092
     - GROUP_ID=1
     - CONFIG_STORAGE_TOPIC=my_connect_configs
     - OFFSET_STORAGE_TOPIC=my_connect_offsets
     - STATUS_STORAGE_TOPIC=my_connect_statuses
